# NumPy 

In [2]:
import numpy as np

## 1. NumPy arrays

In [31]:
#Array of zeros.

array_1D = np.zeros(10, dtype = np.int8) 
array_2D = np.zeros((5,2), dtype = np.float64)  #Data type could be omitted.

print("1D array: {} \n\n2D array: {}".format(array_1D, array_2D))

shape = np.shape(array_2D)
print("\n2D array shape: {}".format(shape))

1D array: [0 0 0 0 0 0 0 0 0 0] 

2D array: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

2D array shape: (5, 2)


In [34]:
#Array from zero with an specified number of elements increasing the value one by one.

array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [35]:
#Array with elements from start to end of a certain size.

array = np.linspace(0, 1, 11)
array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
#Array from a list with integers.

elements = [1, 2, 3, 4, 5]

array = np.array(elements)
array

array([1, 2, 3, 4, 5])

## 2. Randomly generated arrays

In [131]:
#Uniform random numbers between 0 and 1 with an specified shape.

mat = np.random.rand(5, 2)
mat

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [132]:
#Random numbers standard normal distribution.

np.random.seed(2) #Set seed for reproducibility (the randomly is fixed).

mat = np.random.randn(5,2)
mat

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [133]:
#Random integers between 0 and 99.

mat = np.random.randint(low = 0, high = 100, size = (5,2))
mat

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

In [66]:
#Suffled array.

array = np.arange(5)

np.random.shuffle(array)
array

array([4, 1, 0, 3, 2])

## 3. Element-wise operations

In [72]:
np.random.seed(2)
array = np.random.rand(3) #Vector with 3 elements.

arr_exp = np.exp(array)     #Exponential (e^x)
arr_log = np.log(array)     #Log(x)
arr_log1 = np.log1p(array)  #Log(x+1)
arr_sqrt = np.sqrt(array)   #Square root.

arr_round = array.round(3)  #Rounded array to 3th digit.

print("Original array: {}".format(array))
print("\nExp array: {}".format(arr_exp))
print("\nLog(x) array: {}".format(arr_log))
print("\nLog(x+1) array: {}".format(arr_log1))
print("\nSqrt array: {}".format(arr_sqrt))

print("\nRounded array: {}".format(arr_round))


#Other operations: +, -, /, ** (between arrays or an array and an scalar value).

Original array: [0.4359949  0.02592623 0.54966248]

Exp array: [1.54650091 1.02626524 1.73266811]

Log(x) array: [-0.83012473 -3.65250001 -0.59845087]

Log(x+1) array: [0.36185792 0.02559585 0.43803715]

Sqrt array: [0.6602991  0.16101625 0.74139226]

Rounded array: [0.436 0.026 0.55 ]


### 3.1. Comparison operations

In [88]:
np.random.rand(3)
arr1 = np.random.rand(4)
arr2 = np.random.rand(4)

#Comparison operations.

print("Array 1: {}".format(arr1))
print("Array 2: {}".format(arr2))

result1 = arr1 >= 0.5
result2 = arr1 < arr2

print("\nResult 1: {}".format(result1))
print("Result 2: {}".format(result2))

#Comparison operators: <, >, >=, <=

#-----------------------------------------

#Logical operations.

result3 = result1 & result2
result4 = result1 | result2

print("\nAND: {}".format(result3))
print("OR: {}".format(result4))

Array 1: [0.52573325 0.04242919 0.16441909 0.45022718]
Array 2: [0.70797117 0.77758791 0.777103   0.50277875]

Result 1: [ True False False False]
Result 2: [ True  True  True  True]

AND: [ True False False False]
OR: [ True  True  True  True]


### 3.2. Logical operations

In [ ]:
np.random.rand(3)
arr1 = np.random.rand(4)
arr2 = np.random.rand(4)

print("Array 1: {}".format(arr1))
print("Array 2: {}".format(arr2))

result1 = arr1 %
result2 = arr1 < arr2

print("\nResult 1: {}".format(result1))
print("Result 2: {}".format(result2))

#Comparison operators: <, >, >=, <=

### 3.3. Other operations

In [134]:
np.random.rand(3)
array = np.random.rand(4).round(2)

print("Original array: {}".format(array))

print("\nMin = {}".format( array.min() ))                 #Lower value.
print("Max = {}".format( array.max() ))                   #Higher value.
print("Mean = {}".format( array.mean() ))                 #Mean.
print("Standard desviation = {}".format( array.std() ))   #Standard desviation.
print("Sum = {}".format( array.sum() ))                   #Sum of elements.


#For 2D arrays we can specify the axis along which we apply the corresponding operation.

np.random.seed(2)
mat = np.random.rand(5,2).round(2)

max1 = mat.max(axis = 1)
max2 = mat.max(axis = 0)

print("\nOriginal 2D array: {}".format(array2D))
print("\nMax1 = {}".format(max1))  #Applied to each row.              
print("Max2 = {}".format(max2))      #Aplied to each column.              

Original array: [0.43 0.1  0.13 0.6 ]

Min = 0.1
Max = 0.6
Mean = 0.315
Standard desviation = 0.20910523666326483
Sum = 1.26

Original 2D array: [[0.44 0.03]
 [0.55 0.44]
 [0.42 0.33]
 [0.2  0.62]
 [0.3  0.27]]

Max1 = [0.44 0.55 0.42 0.62 0.3 ]
Max2 = [0.55 0.62]


## 4. Sorting

In [117]:
np.random.seed(2)
array = np.random.rand(5).round(2)
print("Original array: {}".format(array))

print("\nSorted array: {}".format(np.sort(array))) #Sorting the array.

indexes = array.argsort()
print("Sorted array indexes: {}".format(indexes))
print("Array using indexes: {}".format( array[indexes] )) #Slicing an array with another array.

Original array: [0.44 0.03 0.55 0.44 0.42]

Sorted array: [0.03 0.42 0.44 0.44 0.55]
Sorted array indexes: [1 4 0 3 2]
Array using indexes: [0.03 0.42 0.44 0.44 0.55]


## 5. Reshaping

In [135]:
mat1 = np.arange(6).reshape(3,2) #number arrows x number columns = number elements.
mat2 = np.arange(6).reshape(3,2, order = 'F') 

print("Matrix 1: {}".format(array1))
print("\nMatrix 2: {}".format(array2))

Matrix 1: [[0 1]
 [2 3]
 [4 5]]

Matrix 2: [[0 3]
 [1 4]
 [2 5]]


### 5.1.Putting multiple arrays together

In [4]:
np.random.seed(2)

mat = np.arange(6).reshape(3,2)
vec = np.arange(3)

print("Vector: {}".format(vec))
print("Matrix: {}".format(mat))

#Only between 1D arrays and between 2D arrays.

mat1 = np.hstack([vec, vec])
mat2 = np.hstack([mat, mat])

mat3 = np.vstack([vec, vec])
mat4 = np.vstack([mat, mat])

#It allows to stack 1D and 2D arrays ->

mat5 = np.column_stack([vec, vec])
mat6 = np.column_stack([vec, mat])  

#For stacking a vector with a matrix, the dimentions must to match.
#Transpose of a matrix: matrix.T

mat7 = np.vstack([vec, mat.T]) #Vector 1x3 and matrix.T 2x3.

print("\nMatrix 1: {}".format(mat1))
print("\nMatrix 2: {}".format(mat2))
print("\nMatrix 3: {}".format(mat3))
print("\nMatrix 4: {}".format(mat4))
print("\nMatrix 5: {}".format(mat5))
print("\nMatrix 6: {}".format(mat6))
print("\nMatrix 7: {}".format(mat7))

Vector: [0 1 2]
Matrix: [[0 1]
 [2 3]
 [4 5]]

Matrix 1: [0 1 2 0 1 2]

Matrix 2: [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]

Matrix 3: [[0 1 2]
 [0 1 2]]

Matrix 4: [[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]

Matrix 5: [[0 0]
 [1 1]
 [2 2]]

Matrix 6: [[0 0 1]
 [1 2 3]
 [2 4 5]]

Matrix 7: [[0 1 2]
 [0 2 4]
 [1 3 5]]


## 6. Slicing and Filtering

### 6.1. Slicing

In [3]:
mat = np.arange(15).reshape(5,3)

print("Matrix: {}".format(mat[:]))      #All rows. 
print("\nMatrix: {}".format(mat[1:3]))
print("\nMatrix: {}".format(mat[: , :1]))
print("\nMatrix: {}".format(mat[1:3, :2]))  #Final position is not included.

vec = np.arange(3)
np.random.shuffle(vec)
print("\nMatrix: {}".format(mat[vec]))

Matrix: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matrix: [[3 4 5]
 [6 7 8]]

Matrix: [[ 0]
 [ 3]
 [ 6]
 [ 9]
 [12]]

Matrix: [[3 4]
 [6 7]]

Matrix: [[3 4 5]
 [0 1 2]
 [6 7 8]]


### 6.2.Filtering

In [48]:
mat = np.arange(15).reshape(5,3)

print("Even numbers?: {}".format(mat[:, 0] % 2 == 1)) #Even numbers in the first column.

print("\nValues: {}".format(mat[mat[:, 0] % 2 == 1]))

Even numbers?: [False  True False  True False]

Values: [[ 3  4  5]
 [ 9 10 11]]


## 7. Linear algebra 

In [65]:
#Inverse
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

X_inv = np.linalg.inv(X)
print("Inverse matrix: {}".format(X_inv))


#Transpose
X_trans = X.T
print("\nMatrix transpose: {}".format(X_trans))


#Multiplication

X_mult = np.dot(X, X_inv)                              #Also vec1.dot(vec2)
print("\nMultiplication matrix: {}".format(X_mult))

Inverse matrix: [[-3.  3. -1.]
 [ 3. -4.  2.]
 [-1.  2. -1.]]

Matrix transpose: [[0 1 2]
 [1 2 3]
 [2 3 3]]

Multiplication matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
